// Package "custom" ties constants to the icons in the "nf-custom" section.
package custom

const (
	Ada             = '\ue6b5'
	Asm             = '\ue6ab'
	Astro           = '\ue6b3'
	Bazel           = '\ue63a'
	C               = '\ue61e'
	Chuck           = '\ue6b6'
	CommonLisp      = '\ue6b0'
	Cpp             = '\ue61d'
	Crystal         = '\ue62f'
	Default         = '\ue612'
	Electron        = '\ue62e'
	Elixir          = '\ue62d'
	Elm             = '\ue62c'
	Emacs           = '\ue632'
	Fennel          = '\ue6af'
	Firebase        = '\ue657'
	Folder          = '\ue5ff'
	FolderConfig    = '\ue5fc'
	FolderGit       = '\ue5fb'
	FolderGitBranch = '\ue5fb'
	FolderGithub    = '\ue5fd'
	FolderNpm       = '\ue5fa'
	FolderOct       = '\ue6ad'
	FolderOpen      = '\ue5fe'
	Go              = '\ue626'
	Home            = '\ue617'
	Kotlin          = '\ue634'
	Msdos           = '\ue629'
	Neovim          = '\ue6ae'
	Orgmode         = '\ue633'
	PlayArrow       = '\ue602'
	Prettier        = '\ue6b4'
	Puppet          = '\ue631'
	Purescript      = '\ue630'
	Ruby            = '\ue605'
	Scheme          = '\ue6b1'
	Toml            = '\ue6b2'
	VLang           = '\ue6ac'
	Vim             = '\ue62b'
	Vitruvian       = '\ue6b7'
	Windows         = '\ue62a'
)
