package ple

const (
	BackslashSeparator             = '\ue0b9'
	BackslashSeparatorRedundant    = '\ue0bf'
	ColumnNumber                   = '\ue0a3'
	CurrentColumn                  = '\ue0a3'
	FlameThick                     = '\ue0c0'
	FlameThickMirrored             = '\ue0c2'
	FlameThin                      = '\ue0c1'
	FlameThinMirrored              = '\ue0c3'
	ForwardslashSeparator          = '\ue0bb'
	ForwardslashSeparatorRedundant = '\ue0bd'
	Honeycomb                      = '\ue0cc'
	HoneycombOutline               = '\ue0cd'
	IceWaveform                    = '\ue0c8'
	IceWaveformMirrored            = '\ue0ca'
	LeftHalfCircleThick            = '\ue0b6'
	LeftHalfCircleThin             = '\ue0b7'
	LeftHardDividerInverse         = '\ue0d7'
	LegoBlockFacing                = '\ue0d0'
	LegoBlockSideways              = '\ue0d1'
	LegoSeparator                  = '\ue0ce'
	LegoSeparatorThin              = '\ue0cf'
	LowerLeftTriangle              = '\ue0b8'
	LowerRightTriangle             = '\ue0ba'
	PixelatedSquaresBig            = '\ue0c6'
	PixelatedSquaresBigMirrored    = '\ue0c7'
	PixelatedSquaresSmall          = '\ue0c4'
	PixelatedSquaresSmallMirrored  = '\ue0c5'
	RightHalfCircleThick           = '\ue0b4'
	RightHalfCircleThin            = '\ue0b5'
	RightHardDividerInverse        = '\ue0d6'
	TrapezoidTopBottom             = '\ue0d2'
	TrapezoidTopBottomMirrored     = '\ue0d4'
	UpperLeftTriangle              = '\ue0bc'
	UpperRightTriangle             = '\ue0be'
)
